//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFinderUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""Witaj w programie FindFlat, który pomaga znaleźć mieszkanie w określonej przez Ciebie okolicy. Aby wyszukiwać oferty w internecie musisz posiadać dostęp do internetu. Wyniki zaisywane są lokalnie na dysku, więc można je przęglądać również w trybie offline""")]
        public string EWWelcomeText {
            get {
                return ((string)(this["EWWelcomeText"]));
            }
            set {
                this["EWWelcomeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Szukaj")]
        public string EWSearch {
            get {
                return ((string)(this["EWSearch"]));
            }
            set {
                this["EWSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zobacz zapisane")]
        public string EWCheckSaved {
            get {
                return ((string)(this["EWCheckSaved"]));
            }
            set {
                this["EWCheckSaved"] = value;
            }
        }
    }
}
